### ISSUE TITLE
Is this project abandoned? 

### ISSUE THREAD

**Issue by drnkwati** [rakit/framework#3]
Does anyone know if this project has been abandoned?

**Comment by emsifa** [comment]
I'm working on another framework and I have no idea to make this framework better. So, maybe yes.

I'm not recommend you to use this framework for production. But if you want to use this, you can submit any question, bug, or idea, I will respond it ASAP.

**Comment by drnkwati** [comment]
Let me just highlight what i loved about this framework
- the way file uploads are handled
- not too many dependencies on third party packages
- lightweight micro framework

However i wished Psr standards were considered during development
Like for the http layer loading loging etc
I would love to be notified when your new framework is ready or maybe a link to the github repo so i can follow. 
Thanks

**Comment by emsifa** [comment]
Thank you for loving this framework. Yes, that was my purposes when I create this framework. :smile: 

No, I'm not about creating another framework. I mean, I'm working fulltime on app that using another (existing) framework.

I will enhance this framework sometime when I have project that not require me to use another framework. But I don't know exactly when. Maybe about few months ahead.

For your suggestion, I will learn onto it. I want implement them as simple as possible and as small as possible.

If you have any idea to implement them, issues and PR are welcome :+1:
